# Generated by Django 5.0.6 on 2024-05-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_certification_c_image_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='c_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
