# Generated by Django 5.0.6 on 2024-05-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_certification_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
    ]
